//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalization
    {
        public System.Guid IDHospitalization { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public string HospitalizationDescription { get; set; }
        public Nullable<System.Guid> IDPetRecord { get; set; }
        public Nullable<System.Guid> IDDoctor { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual PetRecord PetRecord { get; set; }
    }
}
