//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.AestheticService = new HashSet<AestheticService>();
            this.PetRecord = new HashSet<PetRecord>();
            this.PetVaccine = new HashSet<PetVaccine>();
        }
    
        public System.Guid IDPet { get; set; }
        public string PetName { get; set; }
        public Nullable<System.Guid> IDSpecies { get; set; }
        public Nullable<System.Guid> IDCustomer { get; set; }
        public Nullable<decimal> PetWeight { get; set; }
        public Nullable<byte> PetAge { get; set; }


        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AestheticService> AestheticService { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Species Species { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetRecord> PetRecord { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetVaccine> PetVaccine { get; set; }
    }
}
